### ISSUE TITLE
The error message "Host should not be empty"

### ISSUE THREAD

**Issue by austinsonger** [NSWC-Crane/C-PAT#125]
`{"date":"2024-12-20T21:20:37.944Z","level":3,"component":"index","type":"starting","data":{"version":"1.0.0-beta.1","env":{},"dirname":"/Volumes/documents/C-PAT/api","cwd":"/Volumes/documents/C-PAT/api"}}
{"date":"2024-12-20T21:20:37.954Z","level":3,"component":"index","type":"configuration","data":{"version":"1.0.0-beta.1","settings":{"setClassification":"U","lastAccessResolution":60,"responseValidation":"none"},"client":{"authority":"http://localhost:8080/auth/realms/RMFTools","apiBase":"api","disabled":false,"directory":"../client/dist","refreshToken":{"disabled":false},"features":{"marketplaceDisabled":false}},"stigman":{"clientId":"stig-manager","apiUrl":"http://localhost:54000/api"},"tenable":{"url":""},"docs":{"disabled":false,"docsDirectory":"../../docs/_build/html"},"http":{"address":"127.0.0.1","port":8086,"maxJsonBody":"52428800","maxUpload":"52428800","rateLimit":"1000"},"database":{"acquire":30000,"dialect":"mysql","host":"localhost","idle":10000,"port":3306,"schema":"cpat","maxConnections":25,"minConnections":0,"tls":{},"revert":false,"password":false},"swaggerUi":{"enabled":false,"authority":"http://localhost:8080/auth/realms/RMFTools","server":"http://localhost:8086/api","oauth2RedirectUrl":"http://localhost:8086/api-docs/oauth2-redirect.html"},"oauth":{"clientId":"c-pat","authority":"http://192.168.1.101:8080/auth/realms/RMFTools","claims":{"scope":"scope","username":"preferred_username","servicename":"clientId","fullname":"name","firstname":"given_name","lastname":"family_name","privileges":"['realm_access']?.['roles']","email":"email"}},"log":{"level":3,"mode":"combined"}}}
{"date":"2024-12-20T21:20:39.661Z","level":1,"component":"app","type":"uncaught","data":{"generatedMessage":false,"code":"ERR_ASSERTION","actual":"","expected":true,"operator":"==","name":"AssertionError","message":"Host should not be empty","stack":"AssertionError [ERR_ASSERTION]: Host should not be empty\n    at proxy (/Volumes/documents/C-PAT/api/node_modules/express-http-proxy/index.js:27:3)\n    at Object.<anonymous> (/Volumes/documents/C-PAT/api/index.js:104:25)\n    at Module._compile (node:internal/modules/cjs/loader:1256:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)\n    at Module.load (node:internal/modules/cjs/loader:1119:32)\n    at Module._load (node:internal/modules/cjs/loader:960:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)\n    at node:internal/main/run_main_module:23:47"}}`

**Comment by crodriguez6497** [comment]
@austinsonger The error appears to stem from missing env variables, in this case it looks like the host being passed to express-http-proxy for Tenable is empty or undefined. 

I will include a fix for this in rc.3 so that the application will work even if Tenable is not configured. As a temporary workaround you can set temp values for the following fields and it should bypass the error;
TENABLE_URL
TENABLE_ACCESS_KEY
TENABLE_SECRET_KEY
